[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hackaton = "EadAeXF1xWgLFvDrupAPRgrVGW1HBm6omeX36nRhcsLn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
